<?php

namespace App\Models\SIAKAD_MODEL;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class JadwalMataKuliah extends Model
{
    use HasFactory;

    public static function get_jadwal_mata_kuliah($tahun_akademik){
        return DB::connection('siakad')->select("SELECT ROW_NUMBER() OVER (ORDER BY JP.IDJADWALPERKULIAHAN) AS ROW_NUM, JP.IDJADWALPERKULIAHAN AS P_JADWAL_KULIAH_ID, KP.THNAKADEMIK AS P_TAHUN_AKADEMIK, KP.IDKELAS AS P_KELAS_ID, KP.NAMAKELAS AS P_NAMA_KELAS, JP.IDRUANG AS P_RUANG_ID, CAST(JP.KDHARI AS INTEGER) AS P_HARI, JAM.JAMMULAI AS P_JAM_MULAI, JAM.JAMAKHIR AS P_JAM_SELESAI, MK.IDMATAKULIAH AS P_MATAKULIAH_ID, MK.NAMAMATAKULIAH AS P_NAMA_MATA_KULIAH, R.KAPASITAS AS P_KAPASITAS, TRIM(SD.nidn) AS P_DOSEN_ID, NULL AS P_ASISTEN_ID, NULL AS P_NAMA_ASISTEN, KP.KDPROGRAMSTUDI AS P_KD_PRODI, MK.SKS AS P_SKS, 0 AS P_IS_LAB, 1 AS P_ID_JENIS_KELAS_MATAKULIAH FROM AKADEMIK.JADWALPERKULIAHAN JP JOIN AKADEMIK.KELASPERKULIAHAN KP ON JP.IDKELAS = KP.IDKELAS JOIN SARANA.RUANG R ON JP.IDRUANG = R.IDRUANG JOIN SUPPORT.HARI H ON JP.KDHARI = H.KDHARI JOIN AKADEMIK.JAMPERKULIAHAN JAM ON JP.KDJAMPERKULIAHAN = JAM.KDJAMPERKULIAHAN JOIN AKADEMIK.KEGIATANMATAKULIAH KMK ON KP.IDKEGIATANMATAKULIAH = KMK.IDKEGIATANMATAKULIAH JOIN AKADEMIK.MATAKULIAH MK ON KMK.IDMATAKULIAH = MK.IDMATAKULIAH LEFT JOIN AKADEMIK.DOSENKELAS DK ON KP.IDKELAS = DK.IDKELAS INNER JOIN STAF.STAFDOSEN SD ON DK.IDSTAFDOSEN = SD.IDSTAFDOSEN LEFT JOIN SUPPORT.PROGRAMSTUDI PS ON KP.KDPROGRAMSTUDI = PS.KDPROGRAMSTUDI WHERE LENGTH(TRIM(SD.nidn)) >= 10 AND KP.THNAKADEMIK = ?", [
            $tahun_akademik
        ]);
    }

    public static function get_jadwal_mata_kuliah_by_id($jadwal_kuliah_id){
        return DB::connection('siakad')->select('SELECT ROW_NUMBER() OVER (ORDER BY JP.IDJADWALPERKULIAHAN) AS ROW_NUM, JP.IDJADWALPERKULIAHAN AS P_JADWAL_KULIAH_ID, KP.THNAKADEMIK AS P_TAHUN_AKADEMIK, KP.IDKELAS AS P_KELAS_ID, KP.NAMAKELAS AS P_NAMA_KELAS, JP.IDRUANG AS P_RUANG_ID, CAST(JP.KDHARI AS INTEGER) AS P_HARI, JAM.JAMMULAI AS P_JAM_MULAI, JAM.JAMAKHIR AS P_JAM_SELESAI, MK.IDMATAKULIAH AS P_MATAKULIAH_ID, MK.NAMAMATAKULIAH AS P_NAMA_MATA_KULIAH, R.KAPASITAS AS P_KAPASITAS, TRIM(SD.nidn) AS P_DOSEN_ID, NULL AS P_ASISTEN_ID, NULL AS P_NAMA_ASISTEN, KP.KDPROGRAMSTUDI AS P_KD_PRODI, MK.SKS AS P_SKS, 0 AS P_IS_LAB, 1 AS P_ID_JENIS_KELAS_MATAKULIAH FROM AKADEMIK.JADWALPERKULIAHAN JP JOIN AKADEMIK.KELASPERKULIAHAN KP ON JP.IDKELAS = KP.IDKELAS JOIN SARANA.RUANG R ON JP.IDRUANG = R.IDRUANG JOIN SUPPORT.HARI H ON JP.KDHARI = H.KDHARI JOIN AKADEMIK.JAMPERKULIAHAN JAM ON JP.KDJAMPERKULIAHAN = JAM.KDJAMPERKULIAHAN JOIN AKADEMIK.KEGIATANMATAKULIAH KMK ON KP.IDKEGIATANMATAKULIAH = KMK.IDKEGIATANMATAKULIAH JOIN AKADEMIK.MATAKULIAH MK ON KMK.IDMATAKULIAH = MK.IDMATAKULIAH LEFT JOIN AKADEMIK.DOSENKELAS DK ON KP.IDKELAS = DK.IDKELAS INNER JOIN STAF.STAFDOSEN SD ON DK.IDSTAFDOSEN = SD.IDSTAFDOSEN LEFT JOIN SUPPORT.PROGRAMSTUDI PS ON KP.KDPROGRAMSTUDI = PS.KDPROGRAMSTUDI WHERE LENGTH(TRIM(SD.nidn)) >= 10 AND JP.IDJADWALPERKULIAHAN = ?', [
            $jadwal_kuliah_id
        ])[0];
    }

    public static function get_jadwal_kuliah($tahun_akademik){
        return DB::connection('siakad')->select("SELECT * FROM tblJadwalKuliah WHERE tahun_akademik = :tahun_akademik AND fd_id_kls != '-'", [
            'tahun_akademik' => $tahun_akademik
        ]);
    }
}
